import React from 'react';
import { Camera, Calendar, HardDrive, ShieldCheck, AlertCircle, Cpu } from 'lucide-react';
import type { ExifMetadata } from '../types';

interface Props {
  metadata: ExifMetadata;
}

export const ExifForensicsCard: React.FC<Props> = ({ metadata }) => {
  const hasExif = metadata.has_exif;

  return (
    <div className="saas-card-flat p-5 border border-slate-200 bg-white rounded-xl">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 rounded-md bg-emerald-50 text-emerald-600 border border-emerald-100">
            <Camera className="w-4 h-4" />
          </div>
          <div>
            <h4 className="text-sm font-semibold text-slate-900">EXIF Hardware Forensics</h4>
            <p className="text-xs text-slate-500">Camera provenance and digital sensor metadata</p>
          </div>
        </div>

        {hasExif ? (
          <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-0.5 rounded-full">
            <ShieldCheck className="w-3.5 h-3.5" /> Hardware EXIF Present
          </span>
        ) : (
          <span className="inline-flex items-center gap-1 text-xs font-medium text-amber-700 bg-amber-50 border border-amber-200 px-2.5 py-0.5 rounded-full">
            <AlertCircle className="w-3.5 h-3.5" /> Stripped / Synthetic
          </span>
        )}
      </div>

      <div className="grid grid-cols-2 gap-3 text-xs">
        <div className="p-3 rounded-lg bg-slate-50 border border-slate-100">
          <span className="text-slate-500 mb-1 flex items-center gap-1 font-medium">
            <Camera className="w-3.5 h-3.5 text-slate-400" /> Camera Device
          </span>
          <span className="text-slate-900 font-semibold truncate block">
            {metadata.camera_make || metadata.camera_model
              ? `${metadata.camera_make || ''} ${metadata.camera_model || ''}`.trim()
              : 'Not Recorded'}
          </span>
        </div>

        <div className="p-3 rounded-lg bg-slate-50 border border-slate-100">
          <span className="text-slate-500 mb-1 flex items-center gap-1 font-medium">
            <Calendar className="w-3.5 h-3.5 text-slate-400" /> Capture Timestamp
          </span>
          <span className="text-slate-900 font-semibold truncate block">
            {metadata.datetime_original || 'No Timestamp'}
          </span>
        </div>

        <div className="p-3 rounded-lg bg-slate-50 border border-slate-100">
          <span className="text-slate-500 mb-1 flex items-center gap-1 font-medium">
            <HardDrive className="w-3.5 h-3.5 text-slate-400" /> Software / Pipeline
          </span>
          <span className="text-slate-900 font-semibold truncate block">
            {metadata.software || 'Natural Camera Output'}
          </span>
        </div>

        <div className="p-3 rounded-lg bg-slate-50 border border-slate-100">
          <span className="text-slate-500 mb-1 flex items-center gap-1 font-medium">
            <Cpu className="w-3.5 h-3.5 text-slate-400" /> Sensor ISO
          </span>
          <span className="text-slate-900 font-semibold truncate block">
            {metadata.iso_speed ? `ISO ${metadata.iso_speed}` : 'N/A'}
          </span>
        </div>
      </div>

      <p className="mt-3 text-[11px] text-slate-500 leading-relaxed">
        *Synthetic media generated by modern AI generators (e.g. Midjourney, StyleGAN, Stable Diffusion) typically lack genuine hardware EXIF tags, while mobile camera captures preserve hardware records.
      </p>
    </div>
  );
};
